# Generated by Django 4.1.5 on 2023-01-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_article', models.TextField()),
                ('Blog_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
