# Generated by Django 4.1.5 on 2023-01-24 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pradech360', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='For_creatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('_prof_name', models.CharField(max_length=50)),
                ('website_url', models.URLField(max_length=250)),
                ('_email', models.EmailField(max_length=50)),
                ('country_code', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('_city', models.CharField(max_length=50)),
                ('_page_Url', models.URLField(max_length=250)),
                ('_user_Type', models.CharField(max_length=50)),
                ('_obj', models.CharField(max_length=350)),
                ('_how_you_heared_about_us', models.CharField(max_length=50)),
                ('campaign', models.CharField(max_length=50)),
                ('_industry_type', models.CharField(max_length=50)),
                ('sent_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
        migrations.CreateModel(
            name='For_partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('c_code', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('contry', models.CharField(max_length=50)),
                ('sent_date', models.DateField(auto_now_add=True)),
                ('city', models.CharField(max_length=50)),
                ('page_url', models.URLField(max_length=240)),
                ('how_you_heared_about_us', models.CharField(max_length=50)),
                ('Industry_type', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-sent_date']},
        ),
        migrations.AddField(
            model_name='blog',
            name='sent_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
