# Generated by Django 4.1.5 on 2023-01-24 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pradech360', '0002_for_creatives_for_partnership_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='For_partnership',
        ),
        migrations.RenameField(
            model_name='for_creatives',
            old_name='_page_Url',
            new_name='_page_url',
        ),
        migrations.RenameField(
            model_name='for_creatives',
            old_name='_email',
            new_name='email',
        ),
    ]
