# Generated by Django 4.1.5 on 2023-01-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pradech360', '0004_for_partnership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='for_creatives',
            name='campaign',
            field=models.CharField(max_length=1000),
        ),
    ]
